# Generated by Django 4.1.7 on 2023-02-17 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='title', help_text='Note title', max_length=255, null=True, verbose_name='Note title')),
                ('text', models.TextField(blank=True, help_text='Note content', null=True, verbose_name='Note content')),
                ('created', models.DateField(auto_now_add=True, help_text='Note created', verbose_name='Note created')),
                ('author', models.ForeignKey(help_text='Author', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
        ),
    ]
