# Generated by Django 4.1.7 on 2023-02-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, default='title', help_text='Note title', max_length=255, null=True),
        ),
    ]
